language: node_js
node_js:
  - "11"
addons:
  firefox: latest
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run lint
  - npm run build
  - npm test
cache:
  - npm: true
